name: Publish-Tool

on:
  workflow_call:
    inputs:
      dotnet_sdk_version:
        required: true
        type: string
      REPOSITORY_NAME:
        required: true
        type: string
      MORYX_OPTIMIZE_CODE:
        required: true
        type: string
      MORYX_BUILD_CONFIG:
        required: true
        type: string
      MORYX_BUILDNUMBER:
        required: true
        type: string
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE:
        required: true
        type: boolean

jobs:
  Publish:
    if: ${{ github.event_name == 'push' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet_sdk_version }}
  
      - name: Download package artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: artifacts/Packages/

      - name: Publish on MyGet-CI
        if: ${{ github.ref == 'refs/heads/dev' }} # dev branche is published to myget moryx
        shell: pwsh
        env:
          MORYX_NUGET_APIKEY: ${{secrets.MYGET_TOKEN}}
          MORYX_PACKAGE_TARGET: "https://www.myget.org/F/moryx/api/v2/package"
          MORYX_PACKAGE_TARGET_V3: "https://www.myget.org/F/moryx/api/v3/index.json"
        run: ./Build.ps1 -Publish

      #- name: Publish on MyGet-Future
      #  if: ${{ github.ref == 'refs/heads/future' }} # Future branch is published to myget moryx-future
      #  shell: pwsh
      #  env:
      #    MORYX_NUGET_APIKEY: ${{secrets.MYGET_TOKEN}}
      #    MORYX_PACKAGE_TARGET: "https://www.myget.org/F/moryx-future/api/v2/package"
      #    MORYX_PACKAGE_TARGET_V3: "https://www.myget.org/F/moryx-future/api/v3/index.json"
      #  run: ./Build.ps1 -Publish

      - name: Publish on NuGet
        if: ${{ startsWith(github.ref, 'refs/tags/v') }} # Version Tags are published to nuget
        shell: pwsh
        env:
          MORYX_NUGET_APIKEY: ${{secrets.NUGET_TOKEN}}
          MORYX_PACKAGE_TARGET: "https://api.nuget.org/v3/index.json"
          MORYX_PACKAGE_TARGET_V3: "https://api.nuget.org/v3/index.json"
        run: ./Build.ps1 -Publish